import { useEffect,useMemo,useState } from 'react'
import './DqWalkPlanner.css'

const initial={gems:12000,target:60000,mileage:6200,walkMinutes:30,energy:2,goals:['daily','event'],tasks:[{id:'daily',name:'デイリー報酬を回収',minutes:10,priority:5,done:false},{id:'event',name:'開催中イベントを進める',minutes:20,priority:4,done:false},{id:'mileage',name:'マイレージを取りこぼさない',minutes:15,priority:4,done:false},{id:'heart',name:'こころ・ほこらを整理',minutes:20,priority:3,done:false}]}
const load=()=>{try{return {...initial,...JSON.parse(localStorage.getItem('freewalk.plan')||'{}')}}catch{return initial}}
export default function DqWalkPlanner(){const [plan,setPlan]=useState(load),[tab,setTab]=useState('today'),[message,setMessage]=useState('');useEffect(()=>localStorage.setItem('freewalk.plan',JSON.stringify(plan)),[plan]);const update=(key,value)=>setPlan((old)=>({...old,[key]:value}));const toggle=(id)=>update('tasks',plan.tasks.map((task)=>task.id===id?{...task,done:!task.done}:task));const route=useMemo(()=>plan.tasks.filter((t)=>!t.done).sort((a,b)=>b.priority-a.priority).reduce((list,task)=>{const used=list.reduce((sum,t)=>sum+t.minutes,0);return used+task.minutes<=plan.walkMinutes?[...list,task]:list},[]),[plan.tasks,plan.walkMinutes]);const gemRate=Math.min(100,Math.round(plan.gems/plan.target*100));const summonAdvice=plan.gems>=plan.target?'天井分を確保済み。必要な役割を満たす装備か確認して判断。':`あと${(plan.target-plan.gems).toLocaleString()}ジェム。単発の衝動引きを避けて温存がおすすめ。`;const notify=async()=>{if(!('Notification'in window)){setMessage('この端末は通知に対応していません。');return}const permission=await Notification.requestPermission();if(permission==='granted'){new Notification('今日の無課金ウォーク',{body:`${route.length}件・約${route.reduce((s,t)=>s+t.minutes,0)}分の予定です`});setMessage('今日の予定を通知しました。')}else setMessage('通知が許可されませんでした。')};return <main className="dq-tool">
<header className="dq-header"><a href="?tool=dqwalk" className="dq-logo"><i>歩</i><span>FREE WALK<br/><small>無課金作戦室</small></span></a><nav>{[['today','今日やること'],['gems','ジェム計画'],['tasks','期限管理']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav><button className="save-state">端末内に自動保存</button></header>
<section className="dq-hero"><div><p className="dq-eyebrow">F2P DAILY PLANNER / 非公式ファンツール</p><h1>課金しなくても、<br/><em>迷わず強くなる。</em></h1><p>手持ちの時間と無料資源から、今日やることを3つに絞ります。位置情報・アカウント情報は取得しません。</p></div><aside><span>今日歩ける時間</span><strong>{plan.walkMinutes}<small>分</small></strong><input aria-label="今日歩ける時間" type="range" min="10" max="120" step="10" value={plan.walkMinutes} onChange={(e)=>update('walkMinutes',Number(e.target.value))}/><div><button onClick={()=>update('energy',1)} className={plan.energy===1?'active':''}>軽め</button><button onClick={()=>update('energy',2)} className={plan.energy===2?'active':''}>普通</button><button onClick={()=>update('energy',3)} className={plan.energy===3?'active':''}>しっかり</button></div></aside></section>
{tab==='today'&&<section className="dq-section"><div className="section-title"><div><p className="dq-eyebrow">TODAY'S BEST ROUTE</p><h2>今日の無料メニュー</h2></div><button onClick={notify}>予定を通知</button></div><div className="route-list">{route.length?route.map((task,index)=><article key={task.id}><b>0{index+1}</b><div><span>{task.minutes}分</span><h3>{task.name}</h3><p>{index===0?'最優先。短時間でも先に回収します。':'残り時間に合わせて無理なく進めます。'}</p></div><button onClick={()=>toggle(task.id)}>完了</button></article>):<div className="all-done"><strong>今日の予定は完了です</strong><p>無理に周回せず、明日の無料資源に備えましょう。</p></div>}</div>{message&&<p className="dq-message" role="status">{message}</p>}</section>}
{tab==='gems'&&<section className="dq-section gem-grid"><div className="gem-card"><p className="dq-eyebrow">GEM RESERVE</p><h2>ジェム天井貯金</h2><label>現在のジェム<input type="number" min="0" value={plan.gems} onChange={(e)=>update('gems',Math.max(0,Number(e.target.value)))}/></label><label>目標ジェム<input type="number" min="3000" step="3000" value={plan.target} onChange={(e)=>update('target',Math.max(3000,Number(e.target.value)))}/></label><div className="gem-track"><i style={{width:`${gemRate}%`}}/></div><strong>{gemRate}%</strong></div><div className="advice-card"><span>ふくびき判断</span><h3>{summonAdvice}</h3><ul><li>無料・配布ふくびき券を先に使う</li><li>「強そう」ではなく不足役割で判断</li><li>目標未達なら期限直前まで保留</li></ul><p>確率や開催内容はゲーム内のお知らせを必ず確認してください。</p></div></section>}
{tab==='tasks'&&<section className="dq-section"><div className="section-title"><div><p className="dq-eyebrow">NO FOMO CHECKLIST</p><h2>取りこぼし防止</h2></div><span>{plan.tasks.filter((t)=>t.done).length}/{plan.tasks.length} 完了</span></div><div className="task-list">{plan.tasks.map((task)=><label key={task.id} className={task.done?'done':''}><input type="checkbox" checked={task.done} onChange={()=>toggle(task.id)}/><div><strong>{task.name}</strong><small>目安 {task.minutes}分</small></div><select aria-label={`${task.name}の優先度`} value={task.priority} onChange={(e)=>update('tasks',plan.tasks.map((t)=>t.id===task.id?{...t,priority:Number(e.target.value)}:t))}><option value="5">最優先</option><option value="4">高</option><option value="3">普通</option><option value="2">低</option></select></label>)}</div></section>}
<section className="dq-principles"><p className="dq-eyebrow">FREE-TO-PLAY RULES</p><h2>無課金を続ける3原則</h2><div><article><b>01</b><h3>全部やらない</h3><p>期限・報酬・必要時間で選び、疲れる周回は切り上げる。</p></article><article><b>02</b><h3>ジェムは目的買い</h3><p>天井まで貯め、不足している役割を埋める時だけ検討する。</p></article><article><b>03</b><h3>健康を最優先</h3><p>ながらスマホをせず、立入禁止区域や危険な場所へ入らない。</p></article></div></section>
<footer className="dq-footer"><strong>FREE WALK 無課金作戦室</strong><p>本ツールは非公式です。ゲーム画像・ロゴ・内部データを使用せず、自動操作や位置偽装を行いません。</p><a href="https://walk.dragonquest.jp/web/help/" target="_blank" rel="noreferrer">公式の遊び方を確認</a></footer></main>}
